# Generated by Django 3.0.5 on 2020-08-24 03:32

import chat.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200823_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='C:\\Users\\Nouman\\PycharmProjects\\chitchat\\media/my_sell/'), upload_to=chat.models.image_directory_path),
        ),
    ]
