# Generated by Django 3.0.5 on 2020-08-25 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200825_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channel',
        ),
        migrations.AddField(
            model_name='channel',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Thread'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
