# Generated by Django 3.0.5 on 2020-09-03 08:18

import chat.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media//my_sell', location='C:\\Users\\Nouman\\PycharmProjects\\buddychatapp\\media/my_sell'), upload_to=chat.models.image_directory_path),
        ),
    ]
