# Generated by Django 3.0.5 on 2020-10-14 14:11

import chat.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200903_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media//my_sell', location='/home/nomi/buddychatapp/media/my_sell'), upload_to=chat.models.image_directory_path),
        ),
    ]
