# Generated by Django 3.0.5 on 2020-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20201014_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='phone_no',
            field=models.IntegerField(blank=True),
        ),
    ]
