# Generated by Django 3.0.5 on 2020-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20201014_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
